### ISSUE TITLE
RFE: render plugin edit -> set

### ISSUE THREAD

**Issue by jburel** [ome/omero-cli-render#4]
I would suggest to rename the render plugin subcommand ``edit`` to ``set``, i.e. ``bin/omero render set Image:$ID yaml-file.yml``. Atm, it is actually very hard to figure out what this subcommand is meant to be doing, because of this naming and because of the way the help is written (see RFE regarding this below)

Improve the ``bin/omero render -h`` in following sense regarding the ``edit`` subcommand:

  - move the following part into the <subcommand> help

```
 # Edit a rendering setting
    bin/omero render edit Image:1 <YAML or JSON file>
    where the input file contains a top-level channels key (required), and
    an optional top-level greyscale key (True: greyscale, False: colour).
    Channel elements are index:dictionaries of the form:

    channels:
      <index>: (Channel-index, int, 1-based)
        color: <HTML RGB triplet>
        label: <Channel name>
        min: <Minimum (float)>
        max: <Maximum (float)>
        active: <Active (bool)>
      <index>:
        ...
    greyscale: <(bool)>

    # Omitted fields will keep their current values, omitted channel-indices
    # will be turned off.
    bin/omero render edit --copy Screen:1 <YAML or JSON file>
    # Optimised for bulk-rendering, edits the first image and copies the
    # rendering settings to the rest. Note using this flag may have different
    # results from not using it if the images had different settings to begin
    # with and you are only overridding a subset of the settings (all images
    # will end up with the same full rendering settings)
    bin/omero render edit --skipthumbs ...
    # Update rendering settings but don't regenerate thumbnails
```

and reformulate it so that it is understood what the ``--copy`` option is doing (I still do not understand the paragraph. Simon was telling me something in the lines that the first well is being edited (set, changed), whereas for the other wells in a plate the rnd are not set. Instead the rendering settings of the first well are being linked to all the other wells. This is not what I can understand from the ``help`` though (very confusingly written, the ``...Note using this flag may have different results from not using it...`` is just one of the questionable sentences there.

**Comment by jburel** [comment]
PR https://github.com/ome/omero-cli-render/pull/3

**Comment by sbesson** [comment]
The subcommand renaming as well as the help migration should have been carried out as part of #7. There are comments there about the overhaul of help but I would vote for creating a separate issue if still applicable.
